// Logger
export { 
  logger, 
  auditLogger, 
  notificationLogger,
  logNotification,
  logAudit,
  logSecurity,
  logPerformance
} from './logger';

// Metrics
export { 
  metrics,
  register,
  httpRequestDuration,
  httpRequestTotal,
  httpRequestsInProgress,
  notificationsSent,
  notificationDuration,
  notificationsInQueue,
  notificationErrors,
  emailSent,
  emailDuration,
  pushSent,
  pushDuration,
  smsSent,
  smsDuration,
  webhookSent,
  webhookDuration,
  templateRenders,
  templateRenderDuration,
  subscriptionChanges,
  activeSubscriptions,
  systemMemoryUsage,
  systemCpuUsage,
  systemUptime,
  activeUsers,
  totalNotifications,
  notificationDeliveryRate,
  rateLimitViolations,
  errorTotal
} from './metrics';

// Errors
export {
  CustomError,
  AuthenticationError,
  AuthorizationError,
  TokenExpiredError,
  InvalidTokenError,
  NotificationError,
  EmailError,
  PushError,
  SMSError,
  WebhookError,
  ProviderError,
  ProviderNotEnabledError,
  ProviderConfigurationError,
  TemplateError,
  TemplateNotFoundError,
  TemplateRenderError,
  SubscriptionError,
  SubscriptionNotFoundError,
  InvalidSubscriptionError,
  ValidationError,
  InvalidEmailError,
  InvalidPhoneError,
  InvalidWebhookError,
  RateLimitError,
  TooManyRequestsError,
  DatabaseError,
  DatabaseConnectionError,
  ExternalServiceError,
  ServiceUnavailableError,
  NetworkError,
  TimeoutError,
  ConfigurationError,
  MissingConfigurationError,
  BusinessLogicError,
  QuotaExceededError,
  FeatureNotAvailableError,
  handleError,
  formatErrorResponse
} from './errors';

// Validation
export {
  baseNotificationSchema,
  emailNotificationSchema,
  pushNotificationSchema,
  smsNotificationSchema,
  webhookNotificationSchema,
  inAppNotificationSchema,
  notificationSchema,
  subscriptionSchema,
  templateSchema,
  scheduleSchema,
  sendNotificationRequestSchema,
  sendBulkNotificationRequestSchema,
  createSubscriptionRequestSchema,
  updateSubscriptionRequestSchema,
  createTemplateRequestSchema,
  updateTemplateRequestSchema,
  scheduleNotificationRequestSchema,
  notificationQuerySchema,
  subscriptionQuerySchema,
  templateQuerySchema,
  healthCheckSchema,
  validateEmail,
  validatePhone,
  validateWebhookUrl,
  validateCronExpression,
  validateTemplateVariables,
  type EmailNotification,
  type PushNotification,
  type SMSNotification,
  type WebhookNotification,
  type InAppNotification,
  type Notification,
  type Subscription,
  type Template,
  type Schedule
} from './validation';

// Auth
export {
  UserRole,
  Permission,
  rolePermissions,
  JWTPayload,
  APIKeyPayload,
  generateToken,
  generateAPIKeyToken,
  verifyToken,
  verifyAPIKeyToken,
  extractToken,
  extractAPIKey,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  canAccessResource,
  canModifyResource,
  canDeleteResource,
  getPermissionsFromRole,
  rateLimitsByRole,
  notificationQuotasByRole,
  getRateLimitForRole,
  getNotificationQuotaForRole,
  isValidRole,
  isValidPermission
} from './auth.utils';
